# Generated by Django 4.1.3 on 2022-11-25 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                (
                    "sort_by",
                    models.CharField(
                        choices=[("d", "date"), ("r", "rating"), ("a", "alphabet")],
                        default="date",
                        max_length=100,
                    ),
                ),
                ("increasing_order", models.BooleanField(default=False)),
                ("tick", models.BooleanField(default=False)),
                ("color_tags", models.BooleanField(default=False)),
                ("grouping", models.BooleanField(default=False)),
                (
                    "group_by",
                    models.CharField(
                        choices=[("c", "color"), ("t", "tick")],
                        default="tick",
                        max_length=100,
                    ),
                ),
                ("descriptions", models.BooleanField(default=False)),
                (
                    "descriptions_view",
                    models.CharField(
                        choices=[
                            ("f", "first"),
                            ("t", "two"),
                            ("a", "all"),
                            ("n", "none"),
                        ],
                        default="first",
                        max_length=100,
                    ),
                ),
                ("show_date", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["updated"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("ticked", models.BooleanField(default=False)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("rd", "red"),
                            ("oe", "orange"),
                            ("yw", "yellow"),
                            ("gn", "green"),
                            ("be", "blue"),
                            ("pe", "purple"),
                            ("gy", "grey"),
                        ],
                        default="red",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="notes.note",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
