# Generated by Django 4.1.3 on 2022-11-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                (
                    "sort_by",
                    models.CharField(
                        choices=[("d", "date"), ("r", "rating"), ("a", "alphabet")],
                        default="date",
                        max_length=100,
                    ),
                ),
                ("increasing_order", models.BooleanField(default=False)),
                ("tick", models.BooleanField(default=False)),
                ("color_tags", models.BooleanField(default=False)),
                ("grouping", models.BooleanField(default=False)),
                (
                    "group_by",
                    models.CharField(
                        choices=[("c", "color"), ("t", "tick")],
                        default="tick",
                        max_length=100,
                    ),
                ),
                ("descriptions", models.BooleanField(default=False)),
                (
                    "descriptions_view",
                    models.CharField(
                        choices=[
                            ("f", "first"),
                            ("t", "two"),
                            ("a", "all"),
                            ("n", "none"),
                        ],
                        default="first",
                        max_length=100,
                    ),
                ),
                ("show_date", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["updated"],
            },
        ),
    ]
