# Generated by Django 4.1.3 on 2022-11-24 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("ticked", models.BooleanField(default=False)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("rd", "red"),
                            ("oe", "orange"),
                            ("yw", "yellow"),
                            ("gn", "green"),
                            ("be", "blue"),
                            ("pe", "purple"),
                            ("gy", "grey"),
                        ],
                        default="red",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="notes.note",
                    ),
                ),
            ],
        ),
    ]
